export const CustomerService = {
    getData() {
        return [
            {
                customerId: 'C002',
                name: 'Globex Inc',
                email: 'support@globex.com',
                phone: '123-456-7890',
                companyName: 'Globex Inc',
                jobTitle: 'IT Specialist',
                department: 'Technology',
                openTickets: 5,
                closedTickets: 20,
                ticketCategories: ['Technical'],
                avgResponseTime: '2h',
                csatScore: 9,
                preferredContactMethod: 'Phone',
                languagePreference: 'English',
                timeZone: 'PST',
                feedback: ['Very helpful', 'Knowledgeable team']
            },
            {
                customerId: 'C003',
                name: 'Initech',
                email: 'admin@initech.com',
                phone: '987-654-3210',
                companyName: 'Initech',
                jobTitle: 'Project Manager',
                department: 'Operations',
                openTickets: 2,
                closedTickets: 15,
                ticketCategories: ['Billing', 'Technical'],
                avgResponseTime: '4h',
                csatScore: 4.5,
                preferredContactMethod: 'Email',
                languagePreference: 'English',
                timeZone: 'CST',
                feedback: ['Quick resolutions', 'Good support']
            },
            {
                customerId: 'C004',
                name: 'Hooli',
                email: 'info@hooli.com',
                phone: '555-444-6666',
                companyName: 'Hooli',
                jobTitle: 'Sales Executive',
                department: 'Sales',
                openTickets: 1,
                closedTickets: 5,
                ticketCategories: ['Sales'],
                avgResponseTime: '6h',
                csatScore: 4,
                preferredContactMethod: 'Email',
                languagePreference: 'French',
                timeZone: 'CET',
                feedback: ['Good but can improve', 'Satisfactory']
            },
            {
                customerId: 'C005',
                name: 'Vandelay Industries',
                email: 'george@vandelay.com',
                phone: '101-202-3030',
                companyName: 'Vandelay Industries',
                jobTitle: 'Director',
                department: 'Import/Export',
                openTickets: 0,
                closedTickets: 8,
                ticketCategories: ['Shipping', 'Technical'],
                avgResponseTime: '3.5h',
                csatScore: 7,
                preferredContactMethod: 'Phone',
                languagePreference: 'Spanish',
                timeZone: 'GMT',
                feedback: ['Excellent service', 'Very reliable']
            },
            {
                customerId: 'C006',
                name: 'Soylent Corp',
                email: 'customer@soylent.com',
                phone: '333-444-5555',
                companyName: 'Soylent Corp',
                jobTitle: 'Operations Lead',
                department: 'Operations',
                openTickets: 7,
                closedTickets: 12,
                ticketCategories: ['Product Issue', 'Technical'],
                avgResponseTime: '5h',
                csatScore: 4.2,
                preferredContactMethod: 'Chat',
                languagePreference: 'German',
                timeZone: 'CET',
                feedback: ['Good communication', 'Resolved effectively']
            },
            {
                customerId: 'C007',
                name: 'Aperture Science',
                email: 'portal@aperturesci.com',
                phone: '444-555-6666',
                companyName: 'Aperture Science',
                jobTitle: 'Research Scientist',
                department: 'R&D',
                openTickets: 3,
                closedTickets: 9,
                ticketCategories: ['Technical'],
                avgResponseTime: '3h',
                csatScore: 3,
                preferredContactMethod: 'Email',
                languagePreference: 'English',
                timeZone: 'PST',
                feedback: ['Fast and efficient', 'Great knowledge']
            },
            {
                customerId: 'C008',
                name: 'Cyberdyne Systems',
                email: 'helpdesk@cyberdyne.com',
                phone: '666-777-8888',
                companyName: 'Cyberdyne Systems',
                jobTitle: 'CEO',
                department: 'Administration',
                openTickets: 10,
                closedTickets: 50,
                ticketCategories: ['Technical', 'Security'],
                avgResponseTime: '2h',
                csatScore: 4.8,
                preferredContactMethod: 'Phone',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Extremely satisfied', 'Highly recommend']
            },
            {
                customerId: 'C009',
                name: 'Umbrella Corporation',
                email: 'support@umbrella.com',
                phone: '777-888-9999',
                companyName: 'Umbrella Corporation',
                jobTitle: 'Lab Manager',
                department: 'Research',
                openTickets: 6,
                closedTickets: 18,
                ticketCategories: ['Technical'],
                avgResponseTime: '4h',
                csatScore: 1,
                preferredContactMethod: 'Email',
                languagePreference: 'Japanese',
                timeZone: 'JST',
                feedback: ['Polite staff', 'Helpful suggestions']
            },
            {
                customerId: 'C010',
                name: 'Stark Industries',
                email: 'tony@starkindustries.com',
                phone: '888-999-0000',
                companyName: 'Stark Industries',
                jobTitle: 'Owner',
                department: 'Engineering',
                openTickets: 2,
                closedTickets: 20,
                ticketCategories: ['Technical', 'Billing'],
                avgResponseTime: '1h',
                csatScore: 4.9,
                preferredContactMethod: 'Email',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Innovative support', 'Excellent responses']
            },
            {
                customerId: 'C011',
                name: 'Wayne Enterprises',
                email: 'bruce@wayne.com',
                phone: '000-111-2222',
                companyName: 'Wayne Enterprises',
                jobTitle: 'Chairman',
                department: 'Finance',
                openTickets: 0,
                closedTickets: 15,
                ticketCategories: ['Billing', 'Technical'],
                avgResponseTime: '3h',
                csatScore: 8,
                preferredContactMethod: 'Phone',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Very satisfied', 'Quick resolutions']
            },
            {
                customerId: 'C012',
                name: 'Pied Piper',
                email: 'richard@piedpiper.com',
                phone: '222-333-4444',
                companyName: 'Pied Piper',
                jobTitle: 'Founder',
                department: 'Engineering',
                openTickets: 5,
                closedTickets: 22,
                ticketCategories: ['Technical'],
                avgResponseTime: '2h',
                csatScore: 4.8,
                preferredContactMethod: 'Email',
                languagePreference: 'English',
                timeZone: 'PST',
                feedback: ['Great technical knowledge', 'Fast responses']
            },

            {
                customerId: 'C013',
                name: 'Monarch Solutions',
                email: 'contact@monarch.com',
                phone: '444-555-6677',
                companyName: 'Monarch Solutions',
                jobTitle: 'Operations Manager',
                department: 'Logistics',
                openTickets: 3,
                closedTickets: 12,
                ticketCategories: ['Technical', 'Billing'],
                avgResponseTime: '5h',
                csatScore: 4.4,
                preferredContactMethod: 'Chat',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Responsive support', 'Helpful staff']
            },
            {
                customerId: 'C014',
                name: 'Tyrell Corporation',
                email: 'support@tyrellcorp.com',
                phone: '555-666-7788',
                companyName: 'Tyrell Corporation',
                jobTitle: 'Product Manager',
                department: 'R&D',
                openTickets: 1,
                closedTickets: 7,
                ticketCategories: ['Product Issue'],
                avgResponseTime: '4.5h',
                csatScore: 4.6,
                preferredContactMethod: 'Email',
                languagePreference: 'Spanish',
                timeZone: 'CET',
                feedback: ['Knowledgeable team', 'Issues resolved quickly']
            },
            {
                customerId: 'C015',
                name: 'OCP',
                email: 'admin@ocp.com',
                phone: '666-777-8899',
                companyName: 'OCP',
                jobTitle: 'Head of Security',
                department: 'Security',
                openTickets: 8,
                closedTickets: 14,
                ticketCategories: ['Technical', 'Security'],
                avgResponseTime: '3h',
                csatScore: 5,
                preferredContactMethod: 'Phone',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Fast responses', 'Highly satisfied']
            },
            {
                customerId: 'C016',
                name: 'LexCorp',
                email: 'info@lexcorp.com',
                phone: '777-888-9900',
                companyName: 'LexCorp',
                jobTitle: 'CEO',
                department: 'Administration',
                openTickets: 2,
                closedTickets: 25,
                ticketCategories: ['Billing'],
                avgResponseTime: '2h',
                csatScore: 4.8,
                preferredContactMethod: 'Email',
                languagePreference: 'French',
                timeZone: 'GMT',
                feedback: ['Exceptional service', 'Highly recommend']
            },
            {
                customerId: 'C017',
                name: 'Blue Sun Corporation',
                email: 'contact@bluesun.com',
                phone: '888-999-1111',
                companyName: 'Blue Sun Corporation',
                jobTitle: 'Procurement Manager',
                department: 'Purchasing',
                openTickets: 4,
                closedTickets: 9,
                ticketCategories: ['Technical'],
                avgResponseTime: '5h',
                csatScore: 4.5,
                preferredContactMethod: 'Chat',
                languagePreference: 'English',
                timeZone: 'CST',
                feedback: ['Good support', 'Effective solutions']
            },
            {
                customerId: 'C018',
                name: 'Oscorp Industries',
                email: 'helpdesk@oscorp.com',
                phone: '111-222-3333',
                companyName: 'Oscorp Industries',
                jobTitle: 'Research Lead',
                department: 'R&D',
                openTickets: 6,
                closedTickets: 15,
                ticketCategories: ['Technical', 'Product Issue'],
                avgResponseTime: '4h',
                csatScore: 6,
                preferredContactMethod: 'Email',
                languagePreference: 'German',
                timeZone: 'CET',
                feedback: ['Helpful staff', 'Timely solutions']
            },
            {
                customerId: 'C019',
                name: 'Dunder Mifflin',
                email: 'contact@dundermifflin.com',
                phone: '222-333-4444',
                companyName: 'Dunder Mifflin',
                jobTitle: 'Regional Manager',
                department: 'Sales',
                openTickets: 3,
                closedTickets: 20,
                ticketCategories: ['Sales', 'Billing'],
                avgResponseTime: '3h',
                csatScore: 4.6,
                preferredContactMethod: 'Phone',
                languagePreference: 'English',
                timeZone: 'EST',
                feedback: ['Quick and easy support', 'Great staff']
            },
            {
                customerId: 'C020',
                name: 'Nakatomi Corporation',
                email: 'admin@nakatomi.com',
                phone: '333-444-5555',
                companyName: 'Nakatomi Corporation',
                jobTitle: 'Finance Head',
                department: 'Finance',
                openTickets: 1,
                closedTickets: 12,
                ticketCategories: ['Billing'],
                avgResponseTime: '4h',
                csatScore: 8,
                preferredContactMethod: 'Email',
                languagePreference: 'Japanese',
                timeZone: 'JST',
                feedback: ['Professional service', 'Highly satisfied']
            }
        ];
    },

    getCustomersSmall() {
        return Promise.resolve(this.getData().slice(0, 10));
    },

    getCustomersMedium() {
        return Promise.resolve(this.getData().slice(0, 50));
    },

    getCustomersLarge() {
        return Promise.resolve(this.getData().slice(0, 200));
    },

    getCustomersXLarge() {
        return Promise.resolve(this.getData());
    },

    getCustomers(params) {
        const queryParams = params
            ? Object.keys(params)
                  .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(params[k]))
                  .join('&')
            : '';

        return fetch('https://www.primefaces.org/data/customers?' + queryParams).then((res) => res.json());
    }
};
