export const EmployeeService = {
    getData() {
        return [
            {
                employeeId: 'E001',
                name: 'John Doe',
                email: 'john.doe@example.com',
                branch: 'Head Office',
                phone: '123-456-7890',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'IT',
                team: 'Tier 1 Support',
                hireDate: '2020-05-01',
                workShift: '9 AM - 5 PM',
                accessLevel: 'User',
                ticketsResolved: 150,
                avgResolutionTime: '2h 30m',
                csatScore: 4.5,
                slaCompliance: '95%',
                pendingTickets: 5,
                supervisor: 'Jane Smith',
                languages: ['English', 'Spanish'],
                skills: ['Troubleshooting', 'Windows Support'],
                rating: 4.5,
                tickets: {
                    open: 20,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E002',
                name: 'Emily Clark',
                email: 'emily.clark@example.com',
                branch: 'Regional Office',
                phone: '321-654-0987',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'Customer Service',
                team: 'Billing Support',
                hireDate: '2019-08-15',
                workShift: '10 AM - 6 PM',
                accessLevel: 'User',
                ticketsResolved: 200,
                avgResolutionTime: '1h 45m',
                csatScore: 4.8,
                slaCompliance: '98%',
                pendingTickets: 3,
                supervisor: 'Michael Lee',
                languages: ['English', 'French'],
                skills: ['Billing Inquiry', 'Customer Retention'],
                rating: 4.7,
                tickets: {
                    open: 10,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E003',
                name: 'James Turner',
                email: 'james.turner@example.com',
                branch: 'Head Office',
                phone: '456-789-0123',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Lead',
                department: 'IT',
                team: 'Tier 2 Support',
                hireDate: '2018-03-10',
                workShift: '8 AM - 4 PM',
                accessLevel: 'Admin',
                ticketsResolved: 300,
                avgResolutionTime: '1h 30m',
                csatScore: 4.6,
                slaCompliance: '97%',
                pendingTickets: 2,
                supervisor: 'Sarah Adams',
                languages: ['English', 'German'],
                skills: ['Network Support', 'Hardware Issues'],
                rating: 4.8,
                tickets: {
                    open: 5,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E004',
                name: 'Olivia Martinez',
                email: 'olivia.martinez@example.com',
                branch: 'Remote',
                phone: '987-654-3210',
                photo: 'https://via.placeholder.com/150',
                role: 'Technical Specialist',
                department: 'Engineering',
                team: 'Software Support',
                hireDate: '2021-01-20',
                workShift: '11 AM - 7 PM',
                accessLevel: 'User',
                ticketsResolved: 100,
                avgResolutionTime: '3h 15m',
                csatScore: 4.4,
                slaCompliance: '90%',
                pendingTickets: 8,
                supervisor: 'Henry Baker',
                languages: ['English', 'Italian'],
                skills: ['Software Troubleshooting', 'API Support'],
                rating: 4.3,
                tickets: {
                    open: 15,
                    resolved: 10,
                    closed: 10
                }
            },
            {
                employeeId: 'E005',
                name: 'Sophia Johnson',
                email: 'sophia.johnson@example.com',
                branch: 'Regional Office',
                phone: '555-123-4567',
                photo: 'https://via.placeholder.com/150',
                role: 'Customer Service Representative',
                department: 'Customer Service',
                team: 'Account Management',
                hireDate: '2020-11-05',
                workShift: '9 AM - 5 PM',
                accessLevel: 'User',
                ticketsResolved: 175,
                avgResolutionTime: '2h',
                csatScore: 4.7,
                slaCompliance: '93%',
                pendingTickets: 6,
                supervisor: 'Emma Wilson',
                languages: ['English', 'Mandarin'],
                skills: ['Account Queries', 'Renewal Support'],
                rating: 4.6,
                tickets: {
                    open: 40,
                    resolved: 10,
                    closed: 10
                }
            },
            {
                employeeId: 'E006',
                name: 'William Brown',
                email: 'william.brown@example.com',
                branch: 'Head Office',
                phone: '444-987-1234',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'Technical Support',
                team: 'Tier 1 Support',
                hireDate: '2017-07-12',
                workShift: '12 PM - 8 PM',
                accessLevel: 'User',
                ticketsResolved: 225,
                avgResolutionTime: '2h 15m',
                csatScore: 4.3,
                slaCompliance: '96%',
                pendingTickets: 4,
                supervisor: 'Jane Smith',
                languages: ['English', 'Japanese'],
                skills: ['Troubleshooting', 'Linux Support'],
                rating: 4.4,
                tickets: {
                    open: 2,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E007',
                name: 'Mia Davis',
                email: 'mia.davis@example.com',
                branch: 'Remote',
                phone: '333-456-7891',
                photo: 'https://via.placeholder.com/150',
                role: 'Customer Success Manager',
                department: 'Customer Service',
                team: 'Onboarding',
                hireDate: '2019-04-21',
                workShift: '10 AM - 6 PM',
                accessLevel: 'Manager',
                ticketsResolved: 350,
                avgResolutionTime: '1h',
                csatScore: 4.9,
                slaCompliance: '99%',
                pendingTickets: 0,
                supervisor: 'Michael Lee',
                languages: ['English', 'Portuguese'],
                skills: ['Customer Retention', 'Training'],
                rating: 4.9,
                tickets: {
                    open: 15,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E008',
                name: 'Noah Wilson',
                email: 'noah.wilson@example.com',
                branch: 'Head Office',
                phone: '222-345-6789',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Lead',
                department: 'IT',
                team: 'Tier 2 Support',
                hireDate: '2016-09-14',
                workShift: '9 AM - 5 PM',
                accessLevel: 'Admin',
                ticketsResolved: 400,
                avgResolutionTime: '1h 20m',
                csatScore: 4.7,
                slaCompliance: '97%',
                pendingTickets: 1,
                supervisor: 'Sarah Adams',
                languages: ['English', 'Russian'],
                skills: ['Advanced Troubleshooting', 'Server Management'],
                rating: 4.8,
                tickets: {
                    open: 5,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E009',
                name: 'Ava Harris',
                email: 'ava.harris@example.com',
                branch: 'Regional Office',
                phone: '111-234-5678',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'Customer Service',
                team: 'Refund Support',
                hireDate: '2020-02-10',
                workShift: '11 AM - 7 PM',
                accessLevel: 'User',
                ticketsResolved: 180,
                avgResolutionTime: '2h 10m',
                csatScore: 4.6,
                slaCompliance: '94%',
                pendingTickets: 5,
                supervisor: 'Emma Wilson',
                languages: ['English', 'Korean'],
                skills: ['Refund Processing', 'Dispute Resolution'],
                rating: 4.5,
                tickets: {
                    open: 10,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E010',
                name: 'Lucas Moore',
                email: 'lucas.moore@example.com',
                branch: 'Head Office',
                phone: '123-987-6543',
                photo: 'https://via.placeholder.com/150',
                role: 'Technical Specialist',
                department: 'Engineering',
                team: 'API Support',
                hireDate: '2018-06-30',
                workShift: '1 PM - 9 PM',
                accessLevel: 'User',
                ticketsResolved: 210,
                avgResolutionTime: '1h 40m',
                csatScore: 4.7,
                slaCompliance: '92%',
                pendingTickets: 7,
                supervisor: 'Henry Baker',
                languages: ['English', 'Arabic'],
                skills: ['API Debugging', 'Integration Support'],
                rating: 4.7,
                tickets: {
                    open: 20,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E011',
                name: 'Charlotte White',
                email: 'charlotte.white@example.com',
                branch: 'Remote',
                phone: '789-654-3210',
                photo: 'https://via.placeholder.com/150',
                role: 'Customer Service Representative',
                department: 'Customer Service',
                team: 'Subscription Support',
                hireDate: '2021-09-05',
                workShift: '10 AM - 6 PM',
                accessLevel: 'User',
                ticketsResolved: 125,
                avgResolutionTime: '2h 20m',
                csatScore: 4.5,
                slaCompliance: '91%',
                pendingTickets: 6,
                supervisor: 'Emma Wilson',
                languages: ['English', 'Spanish'],
                skills: ['Subscription Management', 'Upselling'],
                rating: 4.4,
                tickets: {
                    open: 30,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E012',
                name: 'Ethan Taylor',
                email: 'ethan.taylor@example.com',
                branch: 'Regional Office',
                phone: '654-123-0987',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'IT',
                team: 'Tier 1 Support',
                hireDate: '2019-07-23',
                workShift: '12 PM - 8 PM',
                accessLevel: 'User',
                ticketsResolved: 190,
                avgResolutionTime: '2h 10m',
                csatScore: 4.3,
                slaCompliance: '92%',
                pendingTickets: 4,
                supervisor: 'Jane Smith',
                languages: ['English', 'French'],
                skills: ['Troubleshooting', 'Software Support'],
                rating: 4.3,
                tickets: {
                    open: 10,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E013',
                name: 'Amelia Lopez',
                email: 'amelia.lopez@example.com',
                branch: 'Head Office',
                phone: '876-543-2109',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Lead',
                department: 'Customer Service',
                team: 'Complaint Resolution',
                hireDate: '2017-04-15',
                workShift: '9 AM - 5 PM',
                accessLevel: 'Admin',
                ticketsResolved: 320,
                avgResolutionTime: '1h 50m',
                csatScore: 4.8,
                slaCompliance: '96%',
                pendingTickets: 3,
                supervisor: 'Michael Lee',
                languages: ['English', 'Portuguese'],
                skills: ['Customer Retention', 'Conflict Management'],
                rating: 4.8,
                tickets: {
                    open: 5,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E014',
                name: 'Benjamin Carter',
                email: 'benjamin.carter@example.com',
                branch: 'Regional Office',
                phone: '543-210-9876',
                photo: 'https://avatar.iran.liara.run/public/50',
                role: 'Technical Specialist',
                department: 'Engineering',
                team: 'Database Support',
                hireDate: '2020-01-10',
                workShift: '1 PM - 9 PM',
                accessLevel: 'User',
                ticketsResolved: 140,
                avgResolutionTime: '2h 45m',
                csatScore: 4.6,
                slaCompliance: '94%',
                pendingTickets: 5,
                supervisor: 'Henry Baker',
                languages: ['English', 'German'],
                skills: ['Database Optimization', 'SQL Support'],
                rating: 4.5,
                tickets: {
                    open: 10,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E015',
                name: 'Isabella Rivera',
                email: 'isabella.rivera@example.com',
                branch: 'Remote',
                phone: '210-987-6543',
                photo: 'https://via.placeholder.com/150',
                role: 'Customer Service Representative',
                department: 'Customer Service',
                team: 'Feedback Management',
                hireDate: '2021-03-18',
                workShift: '11 AM - 7 PM',
                accessLevel: 'User',
                ticketsResolved: 165,
                avgResolutionTime: '2h 5m',
                csatScore: 4.7,
                slaCompliance: '95%',
                pendingTickets: 2,
                supervisor: 'Emma Wilson',
                languages: ['English', 'Italian'],
                skills: ['Feedback Collection', 'Customer Engagement'],
                rating: 4.6,
                tickets: {
                    open: 20,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E016',
                name: 'Elijah Martinez',
                email: 'elijah.martinez@example.com',
                branch: 'Head Office',
                phone: '654-789-3210',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'Technical Support',
                team: 'Tier 1 Support',
                hireDate: '2018-12-01',
                workShift: '10 AM - 6 PM',
                accessLevel: 'User',
                ticketsResolved: 210,
                avgResolutionTime: '1h 50m',
                csatScore: 4.4,
                slaCompliance: '93%',
                pendingTickets: 5,
                supervisor: 'Jane Smith',
                languages: ['English', 'Japanese'],
                skills: ['Software Troubleshooting', 'System Setup'],
                rating: 4.4,
                tickets: {
                    open: 5,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E017',
                name: 'Harper King',
                email: 'harper.king@example.com',
                branch: 'Regional Office',
                phone: '789-123-4560',
                photo: 'https://via.placeholder.com/150',
                role: 'Technical Specialist',
                department: 'Engineering',
                team: 'Hardware Support',
                hireDate: '2019-05-25',
                workShift: '12 PM - 8 PM',
                accessLevel: 'User',
                ticketsResolved: 155,
                avgResolutionTime: '2h 15m',
                csatScore: 4.6,
                slaCompliance: '94%',
                pendingTickets: 3,
                supervisor: 'Henry Baker',
                languages: ['English', 'Mandarin'],
                skills: ['Hardware Diagnostics', 'Peripheral Support'],
                rating: 4.5
            },
            {
                employeeId: 'E018',
                name: 'Avery Hughes',
                email: 'avery.hughes@example.com',
                branch: 'Remote',
                phone: '987-321-6540',
                photo: 'https://via.placeholder.com/150',
                role: 'Customer Success Manager',
                department: 'Customer Service',
                team: 'Onboarding',
                hireDate: '2016-07-19',
                workShift: '9 AM - 5 PM',
                accessLevel: 'Manager',
                ticketsResolved: 380,
                avgResolutionTime: '1h 30m',
                csatScore: 4.9,
                slaCompliance: '99%',
                pendingTickets: 1,
                supervisor: 'Michael Lee',
                languages: ['English', 'Spanish'],
                skills: ['Customer Retention', 'Service Training'],
                rating: 4.9,
                tickets: {
                    open: 2,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E019',
                name: 'Mason Scott',
                email: 'mason.scott@example.com',
                branch: 'Head Office',
                phone: '321-654-7890',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Lead',
                department: 'IT',
                team: 'Tier 2 Support',
                hireDate: '2015-11-30',
                workShift: '8 AM - 4 PM',
                accessLevel: 'Admin',
                ticketsResolved: 420,
                avgResolutionTime: '1h 20m',
                csatScore: 4.7,
                slaCompliance: '96%',
                pendingTickets: 2,
                supervisor: 'Sarah Adams',
                languages: ['English', 'Russian'],
                skills: ['Network Administration', 'Security Support'],
                rating: 4.8,
                tickets: {
                    open: 5,
                    resolved: 30,
                    closed: 10
                }
            },
            {
                employeeId: 'E020',
                name: 'Ella Wright',
                email: 'ella.wright@example.com',
                branch: 'Regional Office',
                phone: '432-567-8901',
                photo: 'https://via.placeholder.com/150',
                role: 'Support Agent',
                department: 'Customer Service',
                team: 'Refund Support',
                hireDate: '2020-06-15',
                workShift: '11 AM - 7 PM',
                accessLevel: 'User',
                ticketsResolved: 200,
                avgResolutionTime: '2h 10m',
                csatScore: 4.8,
                slaCompliance: '97%',
                pendingTickets: 4,
                supervisor: 'Emma Wilson',
                languages: ['English', 'Arabic'],
                skills: ['Refund Processing', 'Conflict Resolution'],
                rating: 4.7,
                tickets: {
                    open: 10,
                    resolved: 30,
                    closed: 10
                }
            }
        ];
    },

    getEmployeesSmall() {
        return Promise.resolve(this.getData().slice(0, 10));
    },

    getEmployeesMedium() {
        return Promise.resolve(this.getData().slice(0, 100));
    },

    getEmployeesLarge() {
        return Promise.resolve(this.getData().slice(0, 200));
    },

    getEmployeesXLarge() {
        return Promise.resolve(this.getData());
    }

    // getEmployees(params) {
    //     const queryParams = params
    //         ? Object.keys(params)
    //               .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(params[k]))
    //               .join('&')
    //         : '';

    //     return fetch('https://www.primefaces.org/data/customers?' + queryParams).then((res) => res.json());
    // }
};
